### ISSUE TITLE
Разные часовые пояса

### ISSUE THREAD

**Issue by velika12** [noggatur/rpg-management#12]
По мере выполнения задачи #11  выяснилось, что нужно не запутаться со временем. В базе данных я хочу хранить время UTC, но при этом время, которое вводит пользователь, нужно переводить в UTC, вычитая таймзону. @noggatur , как насчет того, чтобы делать это прямо в джаваскрипте, хорошая ли это идея? Меня еще интересует вопрос, как мы тогда поступим с напоминаниями пользователю о невыполненных заданиях на почту, которые должны приходить в полночь? Как понимать, в каком часовом поясе человек находится?

**Comment by noggatur** [comment]
@velika12 решили пока не заморачиваться с этим, но всё же без проблем реализуем на JS. будем добавлять на сервер время серверное, и постоянно сверять с пользовательским и конвертировать, если понадобится
