### ISSUE TITLE
Почистить код

### ISSUE THREAD

**Issue by noggatur** [noggatur/rpg-management#13]
Почистить папку `app/views`.

Убрать лишние строчки из когда проекта, которые не несут в себе никакой смысловой нагрузки.

Ключевые моменты закомментировать (и совсем не обязательно на английском! мы же русскоязычные разрабы, так ведь?)

**Comment by velika12** [comment]
Оказалось не так просто. Удалила все шаблоны, которые нужно заменить на оповещения в будущем и получила циклический редирект с профайла на главную и обрано. Разбираться нужно.

Насчет комментирования, я не поддадусь на твои извращения, прости) Каким бы ни был проект, надо писать комментарии, которые потом любой человек сможет понять и прочитать в любом редакторе, в любой кодировке. Мало ли что.

**Comment by noggatur** [comment]
Даша молодец!
