### ISSUE TITLE
SignIn & SignOut

### ISSUE THREAD

**Issue by noggatur** [noggatur/rpg-management#9]
Реализовать вход в систему по паролю (или через соцсеть) и выход из системы при нажатии на кнопочку.

В системе человек должен оставаться **всегда**, пока не нажмёт на кнопку "выйти из системы".
Должна остаться возможность одновременного доступа с нескольких устройств.

**Comment by velika12** [comment]
Будем использовать https://github.com/joscha/play-authenticate для авторизации и https://deadbolt-java.readme.io/docs для контроля прав пользователей. Изначально для авторизации думала воспользоваться http://securesocial.ws/, но она только для версии play 2.3, к сожалению.

**Comment by velika12** [comment]
Регистрация на сайте работает в тестовом режиме. Для отправления письма со ссылкой активации аккаунта необходимо зарегистрировать основную корпоративную почту и указать ее в конфигурации. С нее также впоследствии будут отправляться и напоминания о не доделанных за день заданиях. Этим займусь позже.
